/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Longest.Substring.Without.Repeating.Characters;

import java.util.HashMap;
import java.util.Map;

class Solution {
    public int lengthOfLongestSubstring(String s) {
        if(s.length()==0)return 0;
        
        Map<Character, Integer> chars=new HashMap<>();
        char[] charArr=s.toCharArray();
        int start=0;
        int  max_length=0;

        for(int i=0;i<s.length();i++){
            char c=charArr[i];
            if(chars.containsKey(c)&&chars.get(c)>=start)
            {
                start=chars.get(c);
            }
            chars.put(c, i);
            max_length=Math.max(max_length, i-start);
        }
        return max_length;
    }

    public static void main(String[] args) {
        Solution s=new Solution();
        s.lengthOfLongestSubstring("pwwkew");

    }
}
