/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package LeetCode;

import org.junit.jupiter.api.Test;

import LeetCode.Hard.findMedianSortedArray.AlsoNotTheSolution;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.BeforeEach;

class LongestSubsfindMedianSortedArrayTest {

    @BeforeEach
    public void init(){

    }

    @Test
    public void test1()
    {
        int[] arr1={1, 3};
        int[] arr2={2};
        assertEquals(2, AlsoNotTheSolution.findMedianSortedArrays(arr1, arr2));
    }

    
}
