/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package LeetCode;

import org.junit.jupiter.api.Test;

import LeetCode.Medium.LongestSubstring.LongestSubstringWithoutRepeatingCharacters;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.BeforeEach;

class LongestSubstring {
    private LongestSubstringWithoutRepeatingCharacters s;
    @BeforeEach
    public void init(){
        s=new LongestSubstringWithoutRepeatingCharacters();
    }

    @Test
    void test1()
    {
        assertEquals(3, s.lengthOfLongestSubstring("abcabcbb"));
    }

    @Test
    void test2()
    {
        assertEquals(3, s.lengthOfLongestSubstring("pwwkew"));
    }

    @Test
    void test3()
    {
        assertEquals(1, s.lengthOfLongestSubstring("bbbbb"));
    }
}
